#!/bin/bash
#
# Sets up machine.
#
set -o nounset -o errexit -o pipefail

DOTFILES_DIR="$HOME/dotfiles"
DOTFILES_REPO="git@github.com:fernandoacorreia/dotfiles.git"
KEYFILE="$HOME/.ssh/id_ed25519"

if [ "$UID" == "0" ]; then
  echo Do not run as root.
  exit 1
fi

missing_executable() {
  local executable=$1
  ! [ -x "$(command -v ${executable})" ]
}

macos_cli_dev_tools_installed() {
  xcode-select --print-path &>/dev/null
}

macos_install_cli_dev_tools() {
  if ! macos_cli_dev_tools_installed; then
    echo "Installing command-line developer tools"
    xcode-select --install
    while ! cli_dev_tools_installed; do
      echo "Waiting for installation to finish (look for a dialog window)"
      sleep 10
    done
  fi
}

macos_install_brew() {
  if missing_executable brew; then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
  eval "$(/opt/homebrew/bin/brew shellenv)"
}

macos_install_git() {
  echo "Invoking git to trigger automated setup if it's not installed"
  git --version
}

macos_add_ssh_key_to_agent() {
  echo "Adding ssh key to ssh agent"
  # Set config file
  if ! grep id_ed25519 ~/.ssh/config &>/dev/null; then
    cat <<EOF >> ~/.ssh/config
Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile $KEYFILE
EOF
  fi
  # Start agent
  eval "$(ssh-agent -s)"
  # Add key
  ssh-add --apple-use-keychain "$KEYFILE"
}

macos_create_ssh_key() {
  if ! test -f "$KEYFILE"; then
    echo "Creating ssh key"
    ssh-keygen -t ed25519 -f "$KEYFILE" -C "$(hostname)"
    echo ""
    echo "Add your new public ssh key to your GitHub account and run this script again:"
    echo ""
    cat "${KEYFILE}.pub"
    exit 1
  fi
}

install_apt_packages() {
  sudo apt-get update
  sudo apt-get install -y build-essential git
}

linux_add_ssh_key_to_agent() {
  echo "Adding ssh key to ssh agent"
  # Start agent
  eval "$(ssh-agent -s)"
  # Add key
  ssh-add "$KEYFILE"
}

linux_create_ssh_key() {
  if ! test -f "$KEYFILE"; then
    echo "Creating ssh key"
    ssh-keygen -t ed25519 -f "$KEYFILE" -C "$(hostname)"
    echo ""
    echo "Add your new public ssh key to your GitHub account and run this script again:"
    echo ""
    cat "${KEYFILE}.pub"
    exit 1
  fi
}

install_ansible() {
  if missing_executable ansible-playbook; then
    echo "Installing Ansible"
    brew install ansible
  fi
}

# Sets up linuxbrew on Linux systems and sets the required environment variables on the current shell for Ansible to use it.
setup_linuxbrew() {
  if [[ ! -d $HOME/.linuxbrew/bin ]]; then
    echo "Creating linuxbrew"
    mkdir -p $HOME/.linuxbrew/bin
    ln -s $HOME/dotfiles/vendor/brew $HOME/.linuxbrew/Homebrew
    ln -s $HOME/dotfiles/vendor/brew/bin/brew $HOME/.linuxbrew/bin/brew
  fi
}


install_prerequisites() {
  mkdir -p $HOME/.ssh
  # macOS
  if [ "${OSTYPE//[0-9.]/}" == "darwin" ]; then
    macos_install_cli_dev_tools
    macos_install_brew
    macos_install_git
    macos_create_ssh_key
    macos_add_ssh_key_to_agent
  # Linux Mint Debian Edition / Ubuntu
  elif cat /etc/*release | grep ^NAME | grep -E "LMDE|Ubuntu" &>/dev/null; then
    install_apt_packages
    linux_create_ssh_key
    linux_add_ssh_key_to_agent
    setup_linuxbrew
  else
    echo "Unsupported OS"
    exit 1
  fi
}

clone_repository() {
  if ! test -d $DOTFILES_DIR; then
    echo "Cloning from $DOTFILES_REPO"
    cd $HOME
    git clone --recurse-submodules $DOTFILES_REPO
  fi
}

set_environment() {
  # On Linux, on the first run, the environment for running brew must be set up before installing or running Ansible.
  # This can only be done after the repo has been cloned (because of the symlinks).
  if [[ -d $HOME/.linuxbrew/bin ]]; then
    echo "Setting environment for linuxbrew"
    export PATH=$PATH:$HOME/.linuxbrew/bin
    eval $($HOME/.linuxbrew/bin/brew shellenv)
  fi
}

run_ansible() {
  echo "Running Ansible"
  export ANSIBLE_NOCOWS=1
  cd "$DOTFILES_DIR/ansible"
  PATH="$HOME/.local/bin:$PATH"
  ansible-playbook -i inventory --ask-become-pass playbook.yml
}

install_prerequisites
clone_repository
set_environment
install_ansible
run_ansible
