#!/bin/bash
#
# Builds the dev container image.
#
# Usage: dev/build [--platform PLATFORM]
#
set -o nounset -o errexit -o pipefail
source dev/lib.sh "$@"

docker build --platform "$PLATFORM" \
  --build-arg HOST_UID=$(id -u) \
  --build-arg HOST_GID=$(id -g) \
  -t $IMAGE_NAME -f dev/Dockerfile dev
