#!/bin/bash
#
# Launches a fresh, ephemeral Ubuntu container with dotfiles mounted.
#
set -o nounset -o errexit -o pipefail

IMAGE_NAME="dotfiles-ubuntu-dev"

docker build --platform linux/amd64 -t $IMAGE_NAME dev/dotfiles-ubuntu-dev-image

docker run --platform linux/amd64 --rm -it -v $HOME/.ssh/id_ed25519:/home/ubuntu/.ssh/id_ed25519 -v $(pwd):/home/ubuntu/dotfiles -w /home/ubuntu/dotfiles $IMAGE_NAME
