# fzf:
---
- name: "Check fzf installation status"
  stat:
    path: "{{ homebrew_prefix }}/bin/fzf"
  register: "fzf_check"

- name: "Install fzf"
  command: "{{ home_dir }}/macfiles/bin/brew-install-or-upgrade fzf"
  when: not fzf_check.stat.exists

- name: "Install fzf keybindings and fuzzy completion"
  shell: "{{ homebrew_prefix }}/opt/fzf/install"
  when: not fzf_check.stat.exists
  ignore_errors: yes # see https://github.com/junegunn/fzf/issues/2361
