---
- name: "Check fzf installation status"
  stat:
    path: "{{ homebrew_prefix }}/bin/fzf"
  register: "fzf_check"

- name: "Install fzf"
  command: "{{ home_dir }}/dotfiles/bin/brew-install-or-upgrade fzf"

- name: "Install fzf keybindings and fuzzy completion"
  shell: "{{ homebrew_prefix }}/opt/fzf/install"
