---
- name: Create link for ~/.fzf
  file:
    src: "{{ home_dir }}/dotfiles/vendor/fzf"
    dest: "{{ home_dir }}/.fzf"
    state: link

- name: Install fzf
  shell: "{{ home_dir }}/.fzf/install"
  args:
    creates: "{{ home_dir }}/.fzf.zsh"
