# See https://github.com/pyenv/pyenv
---
- name: Install pyenv on macOS
  when: distribution == 'MacOSX'
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - pyenv
    - pyenv-virtualenv

- name: Install pyenv on Ubuntu
  when: distribution == 'Ubuntu'
  block:
    - name: Install Ubuntu dependencies for building python
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - curl
        - git
        - libbz2-dev
        - libffi-dev
        - liblzma-dev
        - libncurses5-dev
        - libncursesw5-dev
        - libreadline-dev
        - libsqlite3-dev
        - libssl-dev
        - llvm
        - make
        - python-openssl
        - tk-dev
        - wget
        - xz-utils
        - zlib1g-dev
    - name: Run pyenv installer
      shell: "{{ home_dir }}/dotfiles/vendor/pyenv-installer/bin/pyenv-installer"
      args:
        creates: "{{ home_dir }}/.pyenv"
