---
- name: Install node on macOS
  when: distribution == 'MacOSX'
  package:
    name: node
    state: present

- name: Setup node on Linux
  when: distribution != 'MacOSX'
  block:
    - name: Run node pre-setup script on Linux
      become: yes
      shell: "{{ home_dir }}/dotfiles/vendor/nodesource/setup_16.x"
      args:
        creates: "/usr/bin/node" # Skip this step if the step below was ran before.
    - name: Install nodejs on Linux
      become: yes
      package:
        name: nodejs
        state: present
