- name: Check if node is installed
  shell: command -v node
  register: node_check
  ignore_errors: true
  changed_when: false

- name: Install Node.js using nvm
  shell: |
    export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install node
  args:
    executable: /bin/bash
  when: node_check.rc != 0
  environment:
    HOME: "{{ ansible_env.HOME }}"
    XDG_CONFIG_HOME: "{{ ansible_env.XDG_CONFIG_HOME | default('') }}"
