---
- name: "Create symlink to neovim configuration"
  file: src={{ home_dir }}/dotfiles/config/nvim dest={{ home_dir }}/.config/nvim state=link

- name: "Install neovim"
  become: "{{ become_option }}"
  package:
    name: neovim
    state: present
