---
- name: "Create symlink to neovim configuration"
  file: src={{ home_dir }}/macfiles/config/nvim dest={{ home_dir }}/.config/nvim state=link

- name: "Check neovim installation status"
  stat:
    path: "{{ homebrew_prefix }}/bin/nvim"
  register: "neovim_check"

- name: "Install neovim"
  command: "{{ home_dir }}/macfiles/bin/brew-install-or-upgrade neovim"
  when: not neovim_check.stat.exists

- name: "Create symlink to neovim"
  file: src="{{ homebrew_prefix }}/bin/nvim" dest=/usr/local/bin/vi state=link force=yes
  become: yes
