---
- name: "Create symlink to neovim configuration"
  file: src={{ home_dir }}/macfiles/nvim dest={{ home_dir }}/.config/nvim state=link

- name: "Check neovim installation status"
  stat:
    path: "/usr/local/bin/nvim"
  register: "neovim_check"

- name: "Install neovim"
  command: brew install neovim
  when: not neovim_check.stat.exists

- name: "Create symlink to neovim"
  file: src=/usr/local/bin/nvim dest=/usr/local/bin/vi state=link force=yes
  become: yes
