# See https://github.com/cantino/mcfly
---
- name: Install mcfly tap
  shell: |
    if test -f $HOME/.linuxbrew/bin/brew; then
      # Required on Linux machines during first setup
      export PATH=$PATH:$HOME/.linuxbrew/bin
    fi
    brew tap cantino/mcfly https://github.com/cantino/mcfly
  args:
    creates: "{{ homebrew_prefix }}/bin/mcfly"

- name: Install mcfly
  shell: |
    if test -f $HOME/.linuxbrew/bin/brew; then
      # Required on Linux machines during first setup
      export PATH=$PATH:$HOME/.linuxbrew/bin
    fi
    brew install mcfly
  args:
    creates: "{{ homebrew_prefix }}/bin/mcfly"
