---
- name: Set distribution
  set_fact:
    distribution: "{{ ansible_facts['distribution'] }}"

- name: Check if package manager requires root user
  set_fact:
    package_needs_root: "{{ distribution != 'MacOSX' }}"

# See https://stackoverflow.com/a/63734604/376366
- name: Set become option for package
  set_fact:
    become_option: "{{ 'yes' if package_needs_root == True else 'no' }}"

# Work around https://github.com/ansible/ansible/issues/73887
- name: Set pkg_mgr for macOS
  when: distribution == 'MacOSX'
  set_fact:
    pkg_mgr: homebrew
    cacheable: yes

- name: Display distro information
  debug:
    msg: "distribution={{ distribution }}, package_needs_root={{ package_needs_root }}, become_option={{ become_option }}, ansible_facts.pkg_mgr={{ ansible_facts.pkg_mgr }}"

- name: Set Homebrew directory
  set_fact:
    homebrew_prefix: "{{ lookup('env','HOMEBREW_PREFIX') }}"

- name: Get the username running Ansible
  local_action: command whoami
  register: username_on_the_host

- name: Set home directory
  set_fact:
    home_dir: "{{ lookup('env','HOME') }}"

- name: Create basic directories
  file: path={{ home_dir }}/{{ item }} state=directory
  with_items:
    - bin
    - .config
    - projects
    - scratch
    - secrets

- name: Create directory for system-level extra binaries
  become: yes
  file:
    path: /opt/bin
    state: directory
