#!/bin/bash
#
# Installs Docker CE.
#
# See https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04
#
set -o nounset -o errexit -o pipefail

# The name of the user to be added to the docker group must be passed as an argument.
USER_TO_ADD=$1

# Must be sudo
if [[ $UID != 0 ]]; then
  echo "Please run this script with sudo."
  exit 1
fi

# Update existing list of packages
apt-get update

# Install a few prerequisite packages which let apt use packages over HTTPS:
apt-get install -y \
  apt-transport-https \
  ca-certificates \
  curl \
  gnupg \
  lsb-release \
  software-properties-common

# Add the GPG key for the official Docker repository
cat "/home/$USER_TO_ADD/dotfiles/ansible/docker/files/docker-gpg" | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

# Add the Docker repository to APT sources
echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

# Update the package database with the Docker packages from the newly added repo
apt-get update

# install Docker
apt-get install -y docker-ce docker-ce-cli containerd.io

# Add user to docker group
usermod -aG docker ${USER_TO_ADD}

# Configure Docker to start on boot
systemctl enable docker
