---
- name: Install Docker on Linux
  when: distribution != 'MacOSX'
  block:
    - name: Check if Docker is already installed
      stat:
        path: "/usr/bin/docker"
      register: "docker_check"
    - name: Download Docker setup script
      command: curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
      when: not docker_check.stat.exists
    - name: Run Docker setup script
      become: yes
      command: sh /tmp/get-docker.sh
      when: not docker_check.stat.exists
    - name: Add user to docker group
      become: yes
      ansible.builtin.user:
        name: "{{ username_on_the_host.stdout }}"
        group: docker
