---
- name: "Check Cask installation status"
  stat:
    path: "{{ homebrew_prefix }}/Library/Homebrew/cask"
  register: "cask_check"

- name: "Install Cask"
  command: brew tap homebrew/cask
  when: not cask_check.stat.exists
