---
- name: Group hosts by OS
  hosts: all
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: all
  roles:
    - common
    - util
#    - gh
#    - libpq
#    - stern
    - hack-font
    - shell
    - tig
    - pyenv
    - fzf
    - neovim
    - ruby
    - node
    - yarn

- hosts: os_MacOSX
  roles:
    - cask
    - iterm2
    - sourcetree
    - karabiner

# - hosts: os_Ubuntu
#   roles:

# gh
# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
# sudo apt-add-repository https://cli.github.com/packages
# sudo apt update
# sudo apt install gh

# libpq
# sudo apt-get install -y libpq-dev

# stern
# https://github.com/wercker/stern/releases
