---
# See https://stackoverflow.com/a/63734604/376366
- name: Group hosts by OS
  hosts: all
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: all
  roles:
    - common
    - util
    - shell
    - neovim
    - gh
    - libpq
    - stern
    - tig
    - pyenv
    - fzf
    - ruby
    - node
    - yarn
    - sdkman

- hosts: os_MacOSX
  roles:
    - cask
    - hack-font
    - iterm2
    - sourcetree
    - karabiner

- hosts: os_Ubuntu
  roles:
    - linux
    - linuxbrew
    - docker

- hosts: all
  roles:
    - mcfly
    - gitui
    - lazygit
