---
# See https://stackoverflow.com/a/63734604/376366
- name: Group hosts by OS
  hosts: all
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

# Basic settings and utilities
- hosts: all
  roles:
    - common
    - util

# Linux settings and utilities
- hosts: os_LMDE:os_Ubuntu
  roles:
    - linux
    - docker

# Mac settings and utilities
- hosts: os_MacOSX
  roles:
    - cask
    - hack-font
    - iterm2
    - sourcetree
    - karabiner

# General utilities
- hosts: all
  roles:
    - brew-utils
    - fzf
    - gh
    - gitui
    - lazygit
    - libpq
    - mcfly
    - neovim
    - shell
    - stern
    - tig

# Development tools and languages
- hosts: all
  roles:
    - go
    - nvm
    - sdkman
    - dev-tools
