---
- name: Group hosts by OS
  hosts: all
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: all
  roles:
    - common
    - util
    - hack-font
    - shell
    - tig
    - pyenv
    - fzf
    - neovim
    - ruby
    - node
    - yarn

- hosts: os_MacOSX
  roles:
    - cask
    - iterm2
    - sourcetree
    - karabiner

# - hosts: os_Ubuntu
#   roles:
