---
- name: "Check SourceTree installation status"
  stat:
    path: "/Applications/Sourcetree.app"
  register: "sourcetree_check"

- name: "Install SourceTree"
  shell: |
    cd $(mktemp -d -t 'hack')
    curl -L https://product-downloads.atlassian.com/software/sourcetree/ga/Sourcetree_3.0.1_205.zip?_ga=2.187560234.365871195.1547530418-1522429699.1547530418 -o sourcetree.zip
    unzip sourcetree.zip
    mv Sourcetree.app /Applications/
  when: not sourcetree_check.stat.exists
